# Generated by Django 3.0.2 on 2020-01-24 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_auto_20200120_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2020, 1, 24, 11, 30, 35, 409447, tzinfo=utc)),
        ),
    ]
