# Generated by Django 3.0.2 on 2020-02-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aritcle3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('FIELDNAME', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
